### ISSUE TITLE
Error starting 2.1.0-alpha1 after installing

### ISSUE THREAD

**Issue by astro-hemlow** [lisongmechlab/lsml#812] opened 2023-01-31 19:50 UTC
**LSML version:** 2.1.0-alpha1
**Screen resolution:** 
**Operating System:** Windows 10 Pro

**To Reproduce**
1. Try to install the 2.1.0-alpha1 build.

**Actual result:**
Error message (see below). No install.

**Expected behavior**
LSML should install.

**Additional context**

ERROR MESSAGE

java.lang.NoClassDefFoundError: Could not initialize class org.lisoft.lsml.model.database.ChassisDB
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.model.export.garage.LoadoutConverter.parseV2(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.model.export.garage.LoadoutConverter.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convert(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convert(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convert(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.model.export.garage.GarageConverter.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convert(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.TreeUnmarshaller.start(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.XStream.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.XStream.unmarshal(Unknown Source)
  at lsml.merged.module@2.0.9000/com.thoughtworks.xstream.XStream.fromXML(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.model.garage.GarageSerializer.load(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.GlobalGarage$GarageOnDisk.<init>(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.GlobalGarage.openLastGarage(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.LiSongMechLab.foregroundLoad(Unknown Source)
at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.LiSongMechLab.lambda$start$1(Unknown Source)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.DialogErrorReporter.informUser(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.DialogErrorReporter.error(Unknown Source)
  at org.lisoft.lsml@2.0.9000/org.lisoft.lsml.view_fx.DialogErrorReporter.lambda$error$1(Unknown Source)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LiSongMWO** [comment] 2023-01-31 22:56
I cannot reproduce this. Can you please send me the contents of your `%appdata\LiSoft\LSML` directory as well as a copy of your garage please?

**Comment by LiSongMWO** [comment] 2023-02-05 15:22
This was fixed by commit 63150e4, don't know how, but it was.

**Closed as completed by LiSongMWO** 2023-02-05 15:22 UTC
Labels: bug
