### ISSUE TITLE
crash or hang after a bit of use

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#763] opened 2022-01-03 17:13 UTC
**LSML version:** 2.0.14
**Screen resolution:** 3440x1440
**Java version:** 8uX311

**Steps to reproduce issue:**
1. Open LSML
2. Click on import
3. Then load a code from MWO
4. (save to garage or not, cant tell if that matters yet)
4. let sit a while
5. close the new mech file
6. click on import
7. load a code from mwo
8. let sit a while
8. repeat until java and/or li song becomes non responsive.
9. I have briefly seen an exception a few times, but I have not copied it... I'll continue to retry and post here when I can.

**Actual result:**
Java hangs up and lisong mech lab fails to save the garage file ... ive had to redo many mechs now because the garage is not saving prior to this crash/hang

**Expected result:**
prefer it not to hang after some use or just sitting.

**Comment by LiSongMWO** [comment] 2022-01-15 18:00
Hello, I've tried to reproduce this bug but I'm unable to. Can you provide more info? What exact MWO codes are you using? How long to you let it sit for? How much memory do you have? Are you using Oracle Java or OpenJDK?

**Comment by sestrand** [comment] 2022-01-17 14:55
Hi,

Sorry I have not been able to get the exception to display again.  but it
defintely still hangs/crashes. java becomes non responsive in the task
manager.  and as i mentioned, early on I saw an exception at least one
time... but was clicking through and closed it accidentally.

I'll study which codes might be in the mix, but it seems to have been all
of them.  I let it sit for a match or so.  15 minutes?  I have 48 GB of
ram, and I use oracle java.

when it crashes, it will have lost all work since it was last started up.

**Comment by LiSongMWO** [comment] 2022-01-19 13:20
When it happens next time, can you please check memory/CPU usage in task manager? Your description doesn't sound like it would get stuck in an infinete loop and I have no idea how it might leak memory but those metrics might give a direction to look in at least.

**Comment by LiSongMWO** [comment] 2022-01-19 13:43
I tried again today, loaded 20 or so MWO codes, no crash or slow down for me... Are other java applications fine when this happens, just LSML?

**Comment by sestrand** [comment] 2022-01-19 16:02
It’ll be a few weeks before I can try to break it again.  But no, this is
the only Java app that hangs up on me.

**Comment by LiSongMWO** [comment] 2022-02-09 00:29
Going of memory, #145 from way back when was caused by some quite custom setup of windows with many tweaks that for some reason or another Java didn't like and read a weeks stale file from some network drive due whatever cache being left for ages... Eventually the issue resolved after the user re-installed and as far as I know it didn't resurface...

Seeing as I can't reproduce this and none of the people I know who regularly does this kind of usage have reported an issue either, I'm wondering if there's something going on with your particular system. I hate to ask this and I realize it's a lot of work but right now I don't have any other leads; Would it be possible for you to confirm if this is still a problem after a re-install or when running in a VM like OpenBox?

**Comment by sestrand** [comment] 2022-02-09 16:07
I have a standard version of windows.  and reloading that would be a real
pain.  But I have completely uninstalled Java and LSML (other than my
database).  I reinstalled both (now with java 321).  and with teh limited
testing so far, I have not seen this happen again.  Regardless, I will
likely use my new technique to avoid data loss.  that is after some time of
using it and adding mechs etc. I close lsml and reopen it.  that forces a
save of the database, so I dont lose my work.  there is no save button, so
that is the best way to keep from losing my added designs.

**Comment by LiSongMWO** [comment] 2022-02-10 14:29
I added an autosave function in #766 that will be with the next release. And until then, under "Settings" in LSML there's a "Save" button under "Garage" that'll force save the garage.

Since I can't reproduce, I've had no one else reporting this or similar, no stack trace or clear lead on where this might be ocurring and it now seems that it's resolved on your end, I'm going to assume that something had gone sideways with Java on your machine and I'm going to close this as `won't fix` and `not reproducible`. If you do get new freezes/crashes, please feel free to re-open and please try to capture any exceptions you encounter.

**Closed as completed by LiSongMWO** 2022-02-10 14:29 UTC
Labels: wontfix, crash, can't reproduce
