### ISSUE TITLE
Probably short term but BAS-E does not load properly.

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#769] opened 2022-02-09 16:22 UTC
**LSML version:** 2.0.14
**Screen resolution:** 3440x1440
**Java version:** 8u321

**Steps to reproduce issue:**
1. Open LSML
2. export BAS-E or BAS-E(S) with jump jets in leg or body
3. import into LMSL

**Actual result:**
fails to import the jump jets

**Expected result:**
this may be temporary.  the rumor is that there is an error in that the JJs should be limited to just the legs... which should mean that the game's xml files should include those limits and therefore be readable like a few other mechs.  But I dont know what PGI has done exactly and LSML does not either.

**Comment by LiSongMWO** [comment] 2022-02-10 14:31
Can you please provide a MWO code to test with? Also what does "fails to import" mean? Error message? Exception? Nothing at all?

It's not uncommon for PGI to mess up their XML files because they have no validation on it (trust me I've seen them mess up on multiple occasions).

**Comment by sestrand** [comment] 2022-02-10 15:28
sorry, I should have been more complete in my original post.

the stock BAS-E(S) MWO code is

AC=E=0@1|l^p`0=Z7|1C|oB|l^|l^|l^q`0;Z7|1C|oB|h<2|l^rh0@Z7|6S|QC|QCsh0?Z7|6S|QC|QC|l^t41<Z7|LG|LGu41>Z7|LG|LGvB09Z7wJ0F0F0

the detail on the error from LSML is:
Errors occurred while loading BAS-E(S).
As much as possible of the loadout(s) have been loaded.
Details:
Errors for: BAS-E(S)
 - Maximum number of jumpjets already installed
 - Maximum number of jumpjets already installed
 - Maximum number of jumpjets already installed
 - Maximum number of jumpjets already installed

**Comment by LiSongMWO** [comment] 2022-02-10 16:36
Hmmm... The Bloodasp is an Omnimech and as far as I'm aware, whether or not it can equip jump jets depends on if the omnipods it has equipped supports jump jets or not. The `BAS-E(S)` stock omnipods do not thave any hardpoints for jump jets, however the `mech` section in `bas-es.mdf` and also `bas-e.mdf` states `MaxJumpJets="4"`.

It's my understanding that specifying `MaxJumpJets` is not valid on an Omnimech. So it seems to me that this might be a data entry error in the MWO game files, this has happened on multiple occasions in the past so it's in no way a rare occurence... Currenty I believe that LSML correctly reports that the mech cannot equip any jump jets with its current omnipods.

Can you try to save a BAS-E(S) with jump jets in the legs in the ingame mechlab to see if the game will tell you if it's invalid? Will it also let you drop into a match with it? I cannot test because I do not own any Bloodasp.

**Comment by sestrand** [comment] 2022-02-10 16:57
The game allows these jump jets to be installed in the legs or body.  (I
also think there is an error in how they coded this. as an omnipod, it
should only be 2 jjs per leg and only in the legs).

**Comment by sestrand** [comment] 2022-02-10 16:57
and yes you can drop into games with jjs in legs, or body, or ct.

**Comment by LiSongMWO** [comment] 2022-02-10 18:32
Ok, that puts us in the unenviable position to try to decide if this is working as intended from PGI's point of view, in which case I need to make changes in LSML; Or if this is a data entry error and it's a bug that you were able to launch into the game at all in which case we need to complain to PGI.

Is there some tabletop rule or some kind of canon rule around this that we can lean on?

**Comment by sestrand** [comment] 2022-02-10 20:00
https://www.sarna.net/wiki/Blood_Asp refers to the E model as an omnimech
and having 4 jjs.

For what it is worth, MechDB (https://mwo.nav-alpha.com/mechlab/bas-e) has
a similar problem to the LSML.  they cannot install new JJs into the mech
but an import works.

from Mark Nicholson (3d artist / designer / staff) says it was an oops not
to put it in the legs.

https://mwomercs.com/forums/topic/282225-feedback-on-predator-booster-pack/page__p__6442554#entry6442554

**Comment by LiSongMWO** [comment] 2022-02-11 00:21
With that post by PGI and the wording in here: https://www.sarna.net/wiki/Jump_Jet#Fitting_Jump_Jets I believe that LSML is doing the right thing. It's a design decison to not allow invalid loadouts to exist to prevent accidental building of something that would not be possible in game.

Considering that this will be fixed by PGI in the data files eventually, I'm going to close this issue as working as intended. If you disagree, please feel free to re-open.

**Closed as completed by LiSongMWO** 2022-02-11 00:21 UTC
Labels: working as intended

**Comment by sestrand** [comment] 2022-02-28 19:02
BAS E legs now contain the jump jets (like other chassis' omnipods) and LSML loads them properly.
