### ISSUE TITLE
allowable case installation location change not implemented in lsml

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#748] opened 2021-07-29 00:37 UTC
**LSML version:** 2.0.11_64bit
**Screen resolution:** 3440x1440
**Java version:** 8u281

**Steps to reproduce issue:**
1. Open LSML
2. load any IS mech (since it was the biggest change for that type)
3. attempt to place case in any non-torso slot

**Actual result:**
lsml does not recognize that the new build rules in MWO allow case to be placed in all non CT locations.  

**Expected result:**
case is now allowed everywhere.  the parser does well with the weight and space just not all of the new locations.

**Comment by LiSongMWO** [comment] 2021-08-01 14:53
Dupe of #745

**Closed as completed by LiSongMWO** 2021-08-01 14:53 UTC
